# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warstwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(max_length=200, upload_to=b'~')),
                ('czyWektor', models.BooleanField()),
                ('epsg', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
